### PR TITLE
Set the selinux context during the install

### LINKED ISSUE #227: SELinux is preventing (k3s) from execute access on the file k3s
**Describe the bug**
I am trying to get through a first time install of k3s.  I followed the very simple directions and it failed.  

```
This shouldn't take long…
    curl -sfL https://get.k3s.io | sh -
    # Check for Ready node, takes maybe 30 seconds
    k3s kubectl get node
```

**To Reproduce**
```
$ curl -sfL https://get.k3s.io | sh -
[INFO]  Finding latest release
[INFO]  Using v0.2.0 as release
[INFO]  Downloading hash https://github.com/rancher/k3s/releases/download/v0.2.0/sha256sum-amd64.txt
[INFO]  Downloading binary https://github.com/rancher/k3s/releases/download/v0.2.0/k3s
[INFO]  Verifying binary download
[INFO]  Installing k3s to /usr/local/bin/k3s
[sudo] password for dagostinelli: 
[INFO]  Creating /usr/local/bin/kubectl symlink to k3s
[INFO]  Creating /usr/local/bin/crictl symlink to k3s
[INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh
[INFO]  systemd: Creating environment file /etc/systemd/system/k3s.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
[INFO]  systemd: Enabling k3s unit
Created symlink /etc/systemd/system/multi-user.target.wants/k3s.service → /etc/systemd/system/k3s.service.
[INFO]  systemd: Starting k3s
Job for k3s.service failed because the control process exited with error code.
See "systemctl status k3s.service" and "journalctl -xe" for details.
```

Hmm, so:
```
$ sudo systemctl enable k3s
$ sudo systemctl start k3s
Job for k3s.service failed because the control process exited with error code.
See "systemctl status k3s.service" and "journalctl -xe" for details.
```
Then:
```
$ sudo journalctl -xe

Mar 13 21:33:14 mycomputer setroubleshoot[7317]: SELinux is preventing (k3s) from execute access on the file k3s. For complete SELinux messages run: sealert -l cff0b5ab-691a-4e44-b47a-d89a9>
Mar 13 21:33:14 mycomputer python3[7317]: SELinux is preventing (k3s) from execute access on the file k3s.
                                          
                                          *****  Plugin catchall (100. confidence) suggests   **************************
                                          
                                          If you believe that (k3s) should be allowed execute access on the k3s file by default.
                                          Then you should report this as a bug.
                                          You can generate a local policy module to allow this access.
                                          Do
                                          allow this access for now by executing:
                                          # ausearch -c '(k3s)' --raw | audit2allow -M my-k3s
                                          # semodule -X 300 -i my-k3s.pp
```

**Expected behavior**
It should just work as described.

```
This shouldn't take long…
    curl -sfL https://get.k3s.io | sh -
    # Check for Ready node, takes maybe 30 seconds
    k3s kubectl get node
```

**Screenshots**
N/A

**Additional context**
I'm not too keen on "just disable selinux".  I could, however, install the module that audit2allow says to install.  But should I?  Is that what you'd like us to do?  I'll do it, if that's your recommendation.

My machine is Fedora Linux. F29 to be exact.

### PR DESCRIPTION
**Pull request by mrwulf**
Fixes #227

### CODE REVIEW

File: install.sh [hunk 1]
```diff
@@ -262,6 +262,14 @@ setup_binary() {
     info "Installing k3s to ${BIN_DIR}/k3s"
     $SUDO chown root:root ${TMP_BIN}
     $SUDO mv -f ${TMP_BIN} ${BIN_DIR}/k3s
+
+    if [ "Disabled" != `getenforce` ]; then
```
Comment (erikwilson) [inline install.sh]: What happens if selinux/getenforce is not installed?

Comment (mrwulf) [reply install.sh]: I added a check for getenforce

File: install.sh [hunk 2]
```diff
@@ -262,6 +262,14 @@ setup_binary() {
     info "Installing k3s to ${BIN_DIR}/k3s"
     $SUDO chown root:root ${TMP_BIN}
     $SUDO mv -f ${TMP_BIN} ${BIN_DIR}/k3s
+
+    if [ -x `command -v getenforce` ] && [ "Disabled" != `getenforce` ]; then
+        info "SeLinux is enabled, setting permissions"
+        if ! $SUDO semanage fcontext -l | grep "${BIN_DIR}/k3s" > /dev/null 2>&1; then
+            $SUDO semanage fcontext -a -t bin_t "${BIN_DIR}/k3s"
+        fi
+        $SUDO restorecon -v ${BIN_DIR}/k3s > /dev/null
```
Comment (erikwilson) [inline install.sh]: It has been awhile since I have used selinux, so I am not familiar with what exactly is happening here.

Will this work regardless of the selinux policy being used?

Is this permission too permissive for some administrators? Would it be better to provide guidance by pointing to Redhat docs on how to troubleshoot selinux permission issues?

Comment (mrwulf) [reply install.sh]: `semanage` manage creates a file context mapping to mark `k3s` as something that should be runnable. `restorecon` then takes that mapping and applies it to the file itself.

This will set the context if selinux is installed and in a `Permissive` or `Enforcing` policy (actually, anything other than `Disabled`).

I'm sure some admins might want more control, but for the average installer (i.e. someone that is actually using this install script) this change allows instant gratification even when selinux is being used.

**Comment by mrwulf** [comment]
Is anything else needed on this?

**Comment by erikwilson** [comment]
Would it be possible to add some information to the README about adding selinux permissions and the commands to run manually if the systemd installer is not being used?
